DROP DATABASE concesionario;
CREATE DATABASE concesionario;

USE concesionario5;

CREATE TABLE CLIENTE (

COD INT PRIMARY KEY,

NIF CHAR(9) UNIQUE,

NOMBRE VARCHAR(50),

DIRECCION VARCHAR(100),

CIUDAD VARCHAR(20)

 );

CREATE TABLE COCHE (

MATRICULA CHAR(7) PRIMARY KEY,

MARCA VARCHAR(20) NOT NULL,

MODELO VARCHAR(20) NOT NULL,

COLOR VARCHAR(20) CHECK (COLOR IN ('ROJO', 'VERDE', 'AZUL')),

PVP INT CHECK (PVP BETWEEN 10000 AND 40000),

CODCLIENTE INT,

CONSTRAINT fk_codcliente FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(COD) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE REVISION (

 COD INT PRIMARY KEY,

FECHA DATE,

MATRICULA CHAR(7),

CONSTRAINT fk_matricula FOREIGN KEY(MATRICULA) REFERENCES COCHE(MATRICULA) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE OPERACION (

COD INT PRIMARY KEY,

DESCRIPCION VARCHAR(100),

HORAS INT CHECK (HORAS > 0 AND HORAS <= 10)

 );

-- Si quisiéramos crear las restricciones a nivel de tabla y darles un nombre a las -- restricciones fácilmente reconocible la sentencia ddl de creación de esta tabla -- sería:

CREATE TABLE CONSTA (
    CODREVISION INT,
    CODOPERACION INT,
    
    -- Definición de claves foráneas
    CONSTRAINT fk_codrevision FOREIGN KEY (CODREVISION) REFERENCES REVISION(COD) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_codoperacion FOREIGN KEY (CODOPERACION) REFERENCES OPERACION(COD) ON DELETE CASCADE ON UPDATE CASCADE,
    
    -- Definición de clave primaria compuesta
    CONSTRAINT pk_consta PRIMARY KEY (CODREVISION, CODOPERACION)
);


CREATE TABLE MATERIAL (

COD INT PRIMARY KEY,

NOMBRE VARCHAR(50),

PRECIO NUMERIC(2,1)

);


CREATE TABLE NECESITA (

 CODOPERACION INT REFERENCES OPERACION(COD),

CODMATERIAL INT REFERENCES MATERIAL(COD),

CANTIDAD INT,

PRIMARY KEY (CODOPERACION,CODMATERIAL)

 );
