-- =============================================================================
-- SCRIPT DML: CARGA DE PAISES Y MONEDAS DESDE JSON
-- Descripcion: Carga inicial de datos maestros de geopolitica
-- Fuente: assets/json/paises_monedas.json
-- Autor: Equipo de Respuesta Rapida
-- Fecha: 2026-03-16
-- =============================================================================

USE orbita_comercial;

-- =============================================================================
-- PASO 1: CREAR TABLA TEMPORAL PARA CARGA DE JSON
-- =============================================================================

CREATE TABLE IF NOT EXISTS temp_json_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    json_content TEXT
);

-- =============================================================================
-- PASO 2: INSERTAR DATOS DE MONEDAS UNICAS
-- =============================================================================

LOAD DATA INFILE '/ruta/paises_monedas.json' INTO TABLE temp_json_data;


-- =============================================================================
-- PASO 3: INSERTAR MONEDAS UNICAS (extraido de paises_monedas.json)
-- =============================================================================

INSERT INTO geo_monedas (codigo_iso_moneda, nombre_moneda, simbolo_moneda) VALUES
('AFN', 'Afghani', '؋'),
('ALL', 'Lek', 'L'),
('DZD', 'Dinar argelino', 'د.ج'),
('USD', 'Dolar estadounidense', '$'),
('EUR', 'Euro', '€'),
('AOA', 'Kwanza', 'Kz'),
('XCD', 'Dolar del Caribe Oriental', '$'),
('ARS', 'Peso argentino', '$'),
('AMD', 'Dram armenio', '֏'),
('AWG', 'Florin arubeno', 'ƒ'),
('AUD', 'Dolar australiano', '$'),
('AZN', 'Manat azerbaiyano', '₼'),
('BSD', 'Dolar bahameno', '$'),
('BHD', 'Dinar bahreini', '.د.ب'),
('BDT', 'Taka', '৳'),
('BBD', 'Dolar de Barbados', '$'),
('BYN', 'Rublo bielorruso', 'Br'),
('BZD', 'Dolar beliceno', '$'),
('XOF', 'Franco CFA BCEAO', 'Fr'),
('BMD', 'Dolar bermudeno', '$'),
('BTN', 'Ngultrum', 'Nu.'),
('BOB', 'Boliviano', 'Bs.'),
('BAM', 'Marco convertible', 'KM'),
('BWP', 'Pula', 'P'),
('BRL', 'Real brasileño', 'R$'),
('BND', 'Dolar de Brunei', '$'),
('BGN', 'Lev bulgaro', 'лв'),
('BIF', 'Franco burundes', 'Fr'),
('CVE', 'Escudo caboverdiano', '$'),
('KHR', 'Riel', '៛'),
('XAF', 'Franco CFA BEAC', 'Fr'),
('CAD', 'Dolar canadiense', '$'),
('KYD', 'Dolar de las Islas Caiman', '$'),
('CLP', 'Peso chileno', '$'),
('CNY', 'Yuan chino', '¥'),
('COP', 'Peso colombiano', '$'),
('KMF', 'Franco comorense', 'Fr'),
('CDF', 'Franco congoleño', 'Fr'),
('NZD', 'Dolar neozelandes', '$'),
('CRC', 'Colon costarricense', '₡'),
('CUP', 'Peso cubano', '$'),
('ANG', 'Florin antillano', 'ƒ'),
('CZK', 'Corona checa', 'Kč'),
('DKK', 'Corona danesa', 'kr'),
('DJF', 'Franco yibutiano', 'Fr'),
('DOP', 'Peso dominicano', '$'),
('EGP', 'Libra egipcia', '£'),
('ERN', 'Nakfa', 'Nfk'),
('ETB', 'Birr etiope', 'Br'),
('FKP', 'Libra de las Islas Malvinas', '£'),
('FJD', 'Dolar fiyiano', '$'),
('XPF', 'Franco CFP', 'Fr'),
('GMD', 'Dalasi', 'D'),
('GEL', 'Lari', '₾'),
('GHS', 'Cedi', '₵'),
('GIP', 'Libra de Gibraltar', '£'),
('DKK', 'Corona danesa', 'kr'),
('GTQ', 'Quetzal', 'Q'),
('GBP', 'Libra esterlina', '£'),
('GNF', 'Franco guineano', 'Fr'),
('GYD', 'Dolar guyanes', '$'),
('HTG', 'Gourde', 'G'),
('HNL', 'Lempira', 'L'),
('HKD', 'Dolar de Hong Kong', '$'),
('HUF', 'Forinto', 'Ft'),
('ISK', 'Corona islandesa', 'kr'),
('INR', 'Rupia india', '₹'),
('IDR', 'Rupia indonesia', 'Rp'),
('IRR', 'Rial irani', '﷼'),
('IQD', 'Dinar iraqui', 'ع.د'),
('ILS', 'Nuevo shekel israeli', '₪'),
('JMD', 'Dolar jamaiquino', '$'),
('JPY', 'Yen', '¥'),
('JOD', 'Dinar jordano', 'د.ا'),
('KZT', 'Tenge', '₸'),
('KES', 'Chelin keniano', 'Sh'),
('KPW', 'Won norcoreano', '₩'),
('KRW', 'Won surcoreano', '₩'),
('KWD', 'Dinar kuwaiti', 'د.ك'),
('KGS', 'Som', 'с'),
('LAK', 'Kip', '₭'),
('LBP', 'Libra libanesa', 'ل.ل'),
('LSL', 'Loti', 'L'),
('LRD', 'Dolar liberiano', '$'),
('LYD', 'Dinar libio', 'ل.د'),
('CHF', 'Franco suizo', 'Fr'),
('MOP', 'Pataca', 'P'),
('MGA', 'Ariary', 'Ar'),
('MWK', 'Kwacha', 'MK'),
('MYR', 'Ringgit', 'RM'),
('MVR', 'Rupia maldiva', '.ރ'),
('MUR', 'Rupia mauriciana', '₨'),
('MXN', 'Peso mexicano', '$'),
('MDL', 'Leu moldavo', 'L'),
('MNT', 'Tugrik', '₮'),
('MAD', 'Dirham marroqui', 'د.م.'),
('MZN', 'Metical', 'MT'),
('MMK', 'Kyat', 'Ks'),
('NAD', 'Dolar namibio', '$'),
('NPR', 'Rupia nepalesa', '₨'),
('NIO', 'Cordoba', 'C$'),
('NGN', 'Naira', '₦'),
('MKD', 'Denar', 'ден'),
('NOK', 'Corona noruega', 'kr'),
('OMR', 'Rial omani', 'ر.ع.'),
('PKR', 'Rupia pakistani', '₨'),
('PAB', 'Balboa', 'B/.'),
('PGK', 'Kina', 'K'),
('PYG', 'Guarani', '₲'),
('PEN', 'Sol', 'S/'),
('PHP', 'Peso filipino', '₱'),
('PLN', 'Zloty', 'zł'),
('QAR', 'Riyal qatari', 'ر.ق'),
('RON', 'Leu rumano', 'lei'),
('RUB', 'Rublo ruso', '₽'),
('RWF', 'Franco ruandes', 'Fr'),
('SHP', 'Libra de Santa Elena', '£'),
('WST', 'Tala', 'T'),
('STN', 'Dobra', 'Db'),
('SAR', 'Riyal saudi', '﷼'),
('RSD', 'Dinar serbio', 'дин.'),
('SCR', 'Rupia seychelense', '₨'),
('SLE', 'Leone', 'Le'),
('SGD', 'Dolar de Singapur', '$'),
('ANG', 'Florin antillano', 'ƒ'),
('SBD', 'Dolar de las Islas Salomon', '$'),
('SOS', 'Chelin somali', 'Sh'),
('ZAR', 'Rand', 'R'),
('SSP', 'Libra sursudanesa', '£'),
('LKR', 'Rupia de Sri Lanka', '₨'),
('SDG', 'Libra sudanesa', 'ج.س.'),
('SRD', 'Dolar surinames', '$'),
('SEK', 'Corona sueca', 'kr'),
('SYP', 'Libra siria', '£'),
('TWD', 'Nuevo dolar taiwanes', 'NT$'),
('TJS', 'Somoni', 'ЅМ'),
('TZS', 'Chelin tanzano', 'Sh'),
('THB', 'Baht', '฿'),
('TOP', 'Paanga', 'T$'),
('TTD', 'Dolar de Trinidad y Tobago', '$'),
('TND', 'Dinar tunecino', 'د.ت'),
('TRY', 'Lira turca', '₺'),
('TMT', 'Manat turcomano', 'm'),
('UGX', 'Chelin ugandes', 'Sh'),
('UAH', 'Grivna', '₴'),
('AED', 'Dirham de los EAU', 'د.إ'),
('UYU', 'Peso uruguayo', '$'),
('UZS', 'Som uzbeko', 'soʻm'),
('VUV', 'Vatu', 'Vt'),
('VES', 'Bolivar soberano', 'Bs.'),
('VND', 'Dong', '₫'),
('YER', 'Rial yemeni', '﷼'),
('ZMW', 'Kwacha zambiano', 'ZK'),
('ZWL', 'Dolar zimbabuense', '$')
ON DUPLICATE KEY UPDATE 
    nombre_moneda = VALUES(nombre_moneda),
    simbolo_moneda = VALUES(simbolo_moneda);

-- =============================================================================
-- PASO 4: INSERTAR REGIONES
-- =============================================================================

INSERT INTO geo_regiones (nombre_region, descripcion) VALUES
('Europa', 'Region europea incluyendo UE y no UE'),
('America del Norte', 'Estados Unidos, Canada y Mexico'),
('America del Sur', 'Sudamerica y Centroamerica'),
('Asia', 'Asia Oriental, Central y Meridional'),
('Africa', 'Continente africano'),
('Oceania', 'Australia, Nueva Zelanda y territorios del Pacifico'),
('Oriente Medio', 'Region de Medio Oriente'),
('Caribe', 'Islas del Caribe')
ON DUPLICATE KEY UPDATE descripcion = VALUES(descripcion);

-- =============================================================================
-- PASO 5: INSERTAR PAISES (extraido de paises_monedas.json)
-- =============================================================================

INSERT INTO geo_paises (codigo_iso_pais, nombre_pais, id_region_fk, moneda_iso, iva_importacion_pct) VALUES
('AF', 'Afghanistan', 4, 'AFN', 0.00),
('AL', 'Albania', 1, 'ALL', 20.00),
('DZ', 'Algeria', 5, 'DZD', 19.00),
('AS', 'American Samoa', 7, 'USD', 0.00),
('AD', 'Andorra', 1, 'EUR', 4.50),
('AO', 'Angola', 5, 'AOA', 14.00),
('AI', 'Anguilla', 8, 'XCD', 0.00),
('AQ', 'Antarctica', 6, NULL, 0.00),
('AG', 'Antigua and Barbuda', 8, 'XCD', 15.00),
('AR', 'Argentina', 3, 'ARS', 21.00),
('AM', 'Armenia', 4, 'AMD', 20.00),
('AW', 'Aruba', 8, 'AWG', 6.00),
('AU', 'Australia', 6, 'AUD', 10.00),
('AT', 'Austria', 1, 'EUR', 20.00),
('AZ', 'Azerbaijan', 4, 'AZN', 18.00),
('BS', 'Bahamas', 8, 'BSD', 12.00),
('BH', 'Bahrain', 7, 'BHD', 10.00),
('BD', 'Bangladesh', 4, 'BDT', 15.00),
('BB', 'Barbados', 8, 'BBD', 17.50),
('BY', 'Belarus', 1, 'BYN', 20.00),
('BE', 'Belgium', 1, 'EUR', 21.00),
('BZ', 'Belize', 2, 'BZD', 12.50),
('BJ', 'Benin', 5, 'XOF', 18.00),
('BM', 'Bermuda', 8, 'BMD', 0.00),
('BT', 'Bhutan', 4, 'BTN', 0.00),
('BO', 'Bolivia', 3, 'BOB', 13.00),
('BA', 'Bosnia and Herzegovina', 1, 'BAM', 17.00),
('BW', 'Botswana', 5, 'BWP', 12.00),
('BR', 'Brazil', 3, 'BRL', 17.00),
('IO', 'British Indian Ocean Territory', 6, 'USD', 0.00),
('BN', 'Brunei Darussalam', 4, 'BND', 0.00),
('BG', 'Bulgaria', 1, 'BGN', 20.00),
('BF', 'Burkina Faso', 5, 'XOF', 18.00),
('BI', 'Burundi', 5, 'BIF', 18.00),
('CV', 'Cabo Verde', 5, 'CVE', 15.00),
('KH', 'Cambodia', 4, 'KHR', 10.00),
('CM', 'Cameroon', 5, 'XAF', 19.25),
('CA', 'Canada', 2, 'CAD', 5.00),
('KY', 'Cayman Islands', 8, 'KYD', 0.00),
('CF', 'Central African Republic', 5, 'XAF', 19.00),
('TD', 'Chad', 5, 'XAF', 18.00),
('CL', 'Chile', 3, 'CLP', 19.00),
('CN', 'China', 4, 'CNY', 13.00),
('CX', 'Christmas Island', 6, 'AUD', 10.00),
('CC', 'Cocos (Keeling) Islands', 6, 'AUD', 10.00),
('CO', 'Colombia', 3, 'COP', 19.00),
('KM', 'Comoros', 5, 'KMF', 10.00),
('CD', 'Congo (the Democratic Republic of the)', 5, 'CDF', 16.00),
('CG', 'Congo', 5, 'XAF', 18.00),
('CK', 'Cook Islands', 6, 'NZD', 0.00),
('CR', 'Costa Rica', 3, 'CRC', 13.00),
('HR', 'Croatia', 1, 'EUR', 25.00),
('CU', 'Cuba', 3, 'CUP', 0.00),
('CW', 'Curaçao', 8, 'ANG', 6.00),
('CY', 'Cyprus', 1, 'EUR', 19.00),
('CZ', 'Czechia', 1, 'CZK', 21.00),
('CI', 'Cote d\'Ivoire', 5, 'XOF', 18.00),
('DK', 'Denmark', 1, 'DKK', 25.00),
('DJ', 'Djibouti', 5, 'DJF', 10.00),
('DM', 'Dominica', 8, 'XCD', 15.00),
('DO', 'Dominican Republic', 8, 'DOP', 18.00),
('EC', 'Ecuador', 3, 'USD', 12.00),
('EG', 'Egypt', 5, 'EGP', 14.00),
('SV', 'El Salvador', 3, 'USD', 13.00),
('GQ', 'Equatorial Guinea', 5, 'XAF', 15.00),
('ER', 'Eritrea', 5, 'ERN', 0.00),
('EE', 'Estonia', 1, 'EUR', 20.00),
('SZ', 'Eswatini', 5, 'SZL', 15.00),
('ET', 'Ethiopia', 5, 'ETB', 15.00),
('FK', 'Falkland Islands (Malvinas)', 3, 'FKP', 0.00),
('FO', 'Faroe Islands', 1, 'DKK', 25.00),
('FJ', 'Fiji', 6, 'FJD', 9.00),
('FI', 'Finland', 1, 'EUR', 24.00),
('FR', 'France', 1, 'EUR', 20.00),
('GF', 'French Guiana', 3, 'EUR', 0.00),
('PF', 'French Polynesia', 6, 'XPF', 16.00),
('TF', 'French Southern Territories', 6, 'EUR', 0.00),
('GA', 'Gabon', 5, 'XAF', 18.00),
('GM', 'Gambia', 5, 'GMD', 15.00),
('GE', 'Georgia', 4, 'GEL', 18.00),
('DE', 'Germany', 1, 'EUR', 19.00),
('GH', 'Ghana', 5, 'GHS', 12.50),
('GI', 'Gibraltar', 1, 'GIP', 0.00),
('GR', 'Greece', 1, 'EUR', 24.00),
('GL', 'Greenland', 1, 'DKK', 0.00),
('GD', 'Grenada', 8, 'XCD', 15.00),
('GP', 'Guadeloupe', 8, 'EUR', 8.50),
('GU', 'Guam', 6, 'USD', 0.00),
('GT', 'Guatemala', 3, 'GTQ', 12.00),
('GG', 'Guernsey', 1, 'GBP', 0.00),
('GN', 'Guinea', 5, 'GNF', 18.00),
('GW', 'Guinea-Bissau', 5, 'XOF', 18.00),
('GY', 'Guyana', 3, 'GYD', 14.00),
('HT', 'Haiti', 8, 'HTG', 10.00),
('VA', 'Holy See', 1, 'EUR', 0.00),
('HN', 'Honduras', 3, 'HNL', 15.00),
('HK', 'Hong Kong', 4, 'HKD', 0.00),
('HU', 'Hungary', 1, 'HUF', 27.00),
('IS', 'Iceland', 1, 'ISK', 24.00),
('IN', 'India', 4, 'INR', 18.00),
('ID', 'Indonesia', 4, 'IDR', 11.00),
('IR', 'Iran (Islamic Republic of)', 7, 'IRR', 9.00),
('IQ', 'Iraq', 7, 'IQD', 0.00),
('IE', 'Ireland', 1, 'EUR', 23.00),
('IM', 'Isle of Man', 1, 'GBP', 20.00),
('IL', 'Israel', 7, 'ILS', 17.00),
('IT', 'Italy', 1, 'EUR', 22.00),
('JM', 'Jamaica', 8, 'JMD', 15.00),
('JP', 'Japan', 4, 'JPY', 10.00),
('JE', 'Jersey', 1, 'GBP', 5.00),
('JO', 'Jordan', 7, 'JOD', 16.00),
('KZ', 'Kazakhstan', 4, 'KZT', 12.00),
('KE', 'Kenya', 5, 'KES', 16.00),
('KI', 'Kiribati', 6, 'AUD', 0.00),
('KP', 'Korea (the Democratic People\'s Republic of)', 4, 'KPW', 0.00),
('KR', 'Korea (the Republic of)', 4, 'KRW', 10.00),
('KW', 'Kuwait', 7, 'KWD', 0.00),
('KG', 'Kyrgyzstan', 4, 'KGS', 12.00),
('LA', 'Lao People\'s Democratic Republic', 4, 'LAK', 10.00),
('LV', 'Latvia', 1, 'EUR', 21.00),
('LB', 'Lebanon', 7, 'LBP', 11.00),
('LS', 'Lesotho', 5, 'LSL', 15.00),
('LR', 'Liberia', 5, 'LRD', 7.00),
('LY', 'Libya', 5, 'LYD', 0.00),
('LI', 'Liechtenstein', 1, 'CHF', 7.70),
('LT', 'Lithuania', 1, 'EUR', 21.00),
('LU', 'Luxembourg', 1, 'EUR', 17.00),
('MO', 'Macao', 4, 'MOP', 0.00),
('MG', 'Madagascar', 5, 'MGA', 20.00),
('MW', 'Malawi', 5, 'MWK', 16.50),
('MY', 'Malaysia', 4, 'MYR', 10.00),
('MV', 'Maldives', 4, 'MVR', 6.00),
('ML', 'Mali', 5, 'XOF', 18.00),
('MT', 'Malta', 1, 'EUR', 18.00),
('MH', 'Marshall Islands', 6, 'USD', 0.00),
('MQ', 'Martinique', 8, 'EUR', 8.50),
('MR', 'Mauritania', 5, 'MRU', 16.00),
('MU', 'Mauritius', 5, 'MUR', 15.00),
('YT', 'Mayotte', 5, 'EUR', 0.00),
('MX', 'Mexico', 2, 'MXN', 16.00),
('FM', 'Micronesia (Federated States of)', 6, 'USD', 0.00),
('MD', 'Moldova (the Republic of)', 1, 'MDL', 20.00),
('MC', 'Monaco', 1, 'EUR', 20.00),
('MN', 'Mongolia', 4, 'MNT', 10.00),
('ME', 'Montenegro', 1, 'EUR', 21.00),
('MS', 'Montserrat', 8, 'XCD', 0.00),
('MA', 'Morocco', 5, 'MAD', 20.00),
('MZ', 'Mozambique', 5, 'MZN', 17.00),
('MM', 'Myanmar', 4, 'MMK', 5.00),
('NA', 'Namibia', 5, 'NAD', 15.00),
('NR', 'Nauru', 6, 'AUD', 0.00),
('NP', 'Nepal', 4, 'NPR', 13.00),
('NL', 'Netherlands', 1, 'EUR', 21.00),
('NC', 'New Caledonia', 6, 'XPF', 11.00),
('NZ', 'New Zealand', 6, 'NZD', 15.00),
('NI', 'Nicaragua', 3, 'NIO', 15.00),
('NE', 'Niger', 5, 'XOF', 19.00),
('NG', 'Nigeria', 5, 'NGN', 7.50),
('NU', 'Niue', 6, 'NZD', 0.00),
('NF', 'Norfolk Island', 6, 'AUD', 10.00),
('MP', 'Northern Mariana Islands', 6, 'USD', 0.00),
('NO', 'Norway', 1, 'NOK', 25.00),
('OM', 'Oman', 7, 'OMR', 5.00),
('PK', 'Pakistan', 4, 'PKR', 17.00),
('PW', 'Palau', 6, 'USD', 0.00),
('PS', 'Palestine, State of', 7, 'ILS', 17.00),
('PA', 'Panama', 3, 'PAB', 7.00),
('PG', 'Papua New Guinea', 6, 'PGK', 10.00),
('PY', 'Paraguay', 3, 'PYG', 10.00),
('PE', 'Peru', 3, 'PEN', 18.00),
('PH', 'Philippines', 4, 'PHP', 12.00),
('PN', 'Pitcairn', 6, 'NZD', 0.00),
('PL', 'Poland', 1, 'PLN', 23.00),
('PT', 'Portugal', 1, 'EUR', 23.00),
('PR', 'Puerto Rico', 8, 'USD', 11.50),
('QA', 'Qatar', 7, 'QAR', 0.00),
('MK', 'Republic of North Macedonia', 1, 'MKD', 18.00),
('RO', 'Romania', 1, 'RON', 19.00),
('RU', 'Russian Federation', 1, 'RUB', 20.00),
('RW', 'Rwanda', 5, 'RWF', 18.00),
('RE', 'Réunion', 5, 'EUR', 8.50),
('BL', 'Saint Barthélemy', 8, 'EUR', 0.00),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 5, 'SHP', 0.00),
('KN', 'Saint Kitts and Nevis', 8, 'XCD', 17.00),
('LC', 'Saint Lucia', 8, 'XCD', 12.50),
('MF', 'Saint Martin (French part)', 8, 'EUR', 0.00),
('PM', 'Saint Pierre and Miquelon', 8, 'EUR', 0.00),
('VC', 'Saint Vincent and the Grenadines', 8, 'XCD', 15.00),
('WS', 'Samoa', 6, 'WST', 15.00),
('SM', 'San Marino', 1, 'EUR', 0.00),
('ST', 'Sao Tome and Principe', 5, 'STN', 15.00),
('SA', 'Saudi Arabia', 7, 'SAR', 15.00),
('SN', 'Senegal', 5, 'XOF', 18.00),
('RS', 'Serbia', 1, 'RSD', 20.00),
('SC', 'Seychelles', 5, 'SCR', 15.00),
('SL', 'Sierra Leone', 5, 'SLE', 15.00),
('SG', 'Singapore', 4, 'SGD', 8.00),
('SX', 'Sint Maarten (Dutch part)', 8, 'ANG', 5.00),
('SK', 'Slovakia', 1, 'EUR', 20.00),
('SI', 'Slovenia', 1, 'EUR', 22.00),
('SB', 'Solomon Islands', 6, 'SBD', 10.00),
('SO', 'Somalia', 5, 'SOS', 0.00),
('ZA', 'South Africa', 5, 'ZAR', 15.00),
('GS', 'South Georgia and the South Sandwich Islands', 6, 'GBP', 0.00),
('SS', 'South Sudan', 5, 'SSP', 0.00),
('ES', 'Spain', 1, 'EUR', 21.00),
('LK', 'Sri Lanka', 4, 'LKR', 12.00),
('SD', 'Sudan', 5, 'SDG', 0.00),
('SR', 'Suriname', 3, 'SRD', 10.00),
('SJ', 'Svalbard and Jan Mayen', 1, 'NOK', 0.00),
('SE', 'Sweden', 1, 'SEK', 25.00),
('CH', 'Switzerland', 1, 'CHF', 7.70),
('SY', 'Syrian Arab Republic', 7, 'SYP', 0.00),
('TW', 'Taiwan (Province of China)', 4, 'TWD', 5.00),
('TJ', 'Tajikistan', 4, 'TJS', 18.00),
('TZ', 'Tanzania, United Republic of', 5, 'TZS', 18.00),
('TH', 'Thailand', 4, 'THB', 7.00),
('TL', 'Timor-Leste', 4, 'USD', 0.00),
('TG', 'Togo', 5, 'XOF', 18.00),
('TK', 'Tokelau', 6, 'NZD', 0.00),
('TO', 'Tonga', 6, 'TOP', 15.00),
('TT', 'Trinidad and Tobago', 8, 'TTD', 12.50),
('TN', 'Tunisia', 5, 'TND', 19.00),
('TR', 'Turkey', 7, 'TRY', 18.00),
('TM', 'Turkmenistan', 4, 'TMT', 15.00),
('TC', 'Turks and Caicos Islands', 8, 'USD', 0.00),
('TV', 'Tuvalu', 6, 'AUD', 0.00),
('UG', 'Uganda', 5, 'UGX', 18.00),
('UA', 'Ukraine', 1, 'UAH', 20.00),
('AE', 'United Arab Emirates', 7, 'AED', 5.00),
('GB', 'United Kingdom of Great Britain and Northern Ireland', 1, 'GBP', 20.00),
('UM', 'United States Minor Outlying Islands', 6, 'USD', 0.00),
('US', 'United States of America', 2, 'USD', 0.00),
('UY', 'Uruguay', 3, 'UYU', 22.00),
('UZ', 'Uzbekistan', 4, 'UZS', 12.00),
('VU', 'Vanuatu', 6, 'VUV', 12.50),
('VE', 'Venezuela (Bolivarian Republic of)', 3, 'VES', 16.00),
('VN', 'Viet Nam', 4, 'VND', 10.00),
('VG', 'Virgin Islands (British)', 8, 'USD', 0.00),
('VI', 'Virgin Islands (U.S.)', 8, 'USD', 0.00),
('WF', 'Wallis and Futuna', 6, 'XPF', 0.00),
('EH', 'Western Sahara', 5, 'MAD', 20.00),
('YE', 'Yemen', 7, 'YER', 0.00),
('ZM', 'Zambia', 5, 'ZMW', 16.00),
('ZW', 'Zimbabwe', 5, 'ZWL', 14.50),
('AX', 'Åland Islands', 1, 'EUR', 0.00)
ON DUPLICATE KEY UPDATE 
    nombre_pais = VALUES(nombre_pais),
    id_region_fk = VALUES(id_region_fk),
    moneda_iso = VALUES(moneda_iso);

-- =============================================================================
-- LIMPIEZA
-- =============================================================================

DROP TABLE IF EXISTS temp_json_data;

-- =============================================================================
-- VERIFICACION DE CARGA
-- =============================================================================

SELECT 
    'CARGA COMPLETADA' AS estado,
    (SELECT COUNT(*) FROM geo_monedas) AS total_monedas,
    (SELECT COUNT(*) FROM geo_regiones) AS total_regiones,
    (SELECT COUNT(*) FROM geo_paises) AS total_paises;
